#!/usr/bin/env python3
"""Ingest GTFOBins (from a public GTFOBins checkout) into an Ariadne knowledge fact-base.

Each per-binary GTFOBins file is YAML:
    functions:
      <function>:            # capability: file-read, shell, command, suid, sudo, ...
      - code: ...
        contexts:            # privilege vector: suid, sudo, capabilities, ...
          suid:
          sudo:

We emit one fact per (binary, function, context):
    [gtfobin, <binary>, <function>, <context>]
plus a JSON side-file mapping each triple to its example code (for reporting).

Run:  python3 tools/ingest_gtfobins.py data/gtfobins_raw
Out:  ariadne/corpus/knowledge/gtfobins.yaml   (facts)
      ariadne/corpus/knowledge/gtfobins_codes.json  (triple -> code)
"""
import sys
import os
import re
import json
import glob
import yaml

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_YAML = os.path.join(HERE, "ariadne", "corpus", "knowledge", "gtfobins.yaml")
OUT_CODES = os.path.join(HERE, "ariadne", "corpus", "knowledge", "gtfobins_codes.json")


def binary_name(path):
    b = os.path.basename(path)
    m = re.match(r"_gtfobins__(.+)\.txt$", b)
    return m.group(1) if m else b.replace(".txt", "")


def main(raw_dir):
    files = sorted(glob.glob(os.path.join(raw_dir, "_gtfobins__*.txt")))
    facts = []
    codes = {}
    seen = set()
    n_bin = 0
    for path in files:
        try:
            with open(path) as f:
                doc = yaml.safe_load(f)
        except Exception:
            continue
        if not isinstance(doc, dict):
            continue
        funcs = doc.get("functions") or {}
        if not isinstance(funcs, dict):
            continue
        binary = binary_name(path)
        n_bin += 1
        for func, entries in funcs.items():
            if not isinstance(entries, list):
                continue
            for entry in entries:
                if not isinstance(entry, dict):
                    continue
                ctxs = entry.get("contexts") or {"unprivileged": None}
                code = (entry.get("code") or "").strip()
                for ctx in (ctxs.keys() if isinstance(ctxs, dict) else ["unprivileged"]):
                    triple = (binary, func, ctx)
                    if triple in seen:
                        continue
                    seen.add(triple)
                    facts.append(["gtfobin", binary, func, ctx])
                    if code:
                        codes["|".join(triple)] = code
    facts.sort()
    header = ("# GENERATED by tools/ingest_gtfobins.py from GTFOBins (a public GTFOBins checkout).\n"
              "# One fact per (binary, function, context). Loaded as universal knowledge.\n"
              f"# {n_bin} binaries -> {len(facts)} gtfobin facts.\n")
    with open(OUT_YAML, "w") as f:
        f.write(header)
        yaml.safe_dump({"facts": facts}, f, default_flow_style=True, width=200)
    with open(OUT_CODES, "w") as f:
        json.dump(codes, f, indent=0)
    # quick coverage report
    from collections import Counter
    by_func = Counter(t[2] for t in [tuple(x[1:]) for x in facts])
    by_ctx = Counter(t[2] for t in facts)
    print(f"binaries={n_bin}  facts={len(facts)}")
    print("top functions:", Counter(f[2] for f in facts).most_common(8))
    print("contexts:", Counter(f[3] for f in facts).most_common())
    print("wrote", OUT_YAML)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "data", "gtfobins_raw"))
